# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CLN' do
    pod 'AsyncImageView'
    pod 'MFSideMenu'
    pod 'AFNetworking', '~> 2.2'
    pod 'MagicalRecord'
    pod 'HexColors'
end

target 'CLNTests' do

end

